//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by bj.rc
//
#define IDM_ABOUTBOX                    0x0010
#define ID_MENU_HELP_ABOUT              0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BJ_DIALOG                   102
#define IDD_SETTINGS_DIALOG             103
#define IDR_MAINFRAME                   128
#define IDR_ACCELERATOR1                129
#define IDR_MENU_DLG                    131
#define IDD_DIALOG_CASINO_RULES         132
#define IDD_DIALOG_MISTAKES             133
#define IDD_DIALOG_PRACTICE             134
#define IDR_MENU_PRACTICE               135
#define IDD_DIALOG_BID_SETTINGS         136
#define IDD_DIALOG_PLAY_SETTINGS        137
#define IDD_DIALOG_CASINO_SETTINGS      139
#define IDD_DIALOG_STANDARD_STRATEGY    140
#define IDR_MENU_MISTAKES               143
#define IDI_ICON1                       146
#define IDB_BITMAP1                     148
#define IDB_BITMAP_BACK                 150
#define IDD_DIALOG_COUNT                151
#define IDC_EDIT1                       1000
#define IDC_EDIT_MONEY                  1000
#define IDC_EDIT_TOTAL_MISTAKES         1000
#define IDC_EDIT_HIGH_BID               1000
#define IDC_EDIT_PLAY_SPEED             1000
#define IDC_EDIT_NUM_SPLITS             1000
#define IDC_EDIT_COUNT                  1000
#define IDC_BUTTON_DEAL                 1001
#define IDC_EDIT_BET_MISTAKES           1001
#define IDC_EDIT_LOW_BID                1001
#define IDC_EDIT_NUM_PLAYERS            1001
#define IDC_EDIT2                       1002
#define IDC_EDIT_PLAY_MISTAKES          1002
#define IDC_EDIT_PENETRATION            1002
#define IDC_EDIT3                       1003
#define IDC_EDIT_TOTAL_POSSIBLE         1003
#define IDC_EDIT4                       1004
#define IDC_EDIT_TOTAL_ACTUAL           1004
#define IDC_EDIT5                       1005
#define IDC_EDIT_TOTAL_MISTAKES2        1005
#define IDC_EDIT6                       1006
#define IDC_EDIT_BET_MISTAKES2          1006
#define IDC_EDIT7                       1007
#define IDC_EDIT_PLAY_MISTAKES2         1007
#define IDC_EDIT8                       1008
#define IDC_EDIT_TOTAL_POSSIBLE2        1008
#define IDC_EDIT9                       1009
#define IDC_EDIT_TOTAL_ACTUAL2          1009
#define IDC_EDIT10                      1010
#define IDC_EDIT_ACTUAL_WIN             1010
#define IDC_EDIT11                      1011
#define IDC_EDIT_WIN_HAND               1011
#define IDC_EDIT12                      1012
#define IDC_EDIT_AVG_STANDARD_COUNT     1012
#define IDC_EDIT13                      1013
#define IDC_EDIT_THEORETICAL_WIN        1013
#define IDC_EDIT14                      1014
#define IDC_EDIT15                      1015
#define IDC_EDIT16                      1016
#define IDC_EDIT17                      1017
#define IDC_EDIT18                      1018
#define IDC_EDIT19                      1019
#define IDC_EDIT20                      1020
#define IDC_EDIT21                      1021
#define IDC_EDIT22                      1022
#define IDC_RADIO_DEALER                1023
#define IDC_RADIO_ME2                   1023
#define IDC_RADIO_ME                    1024
#define IDC_RADIO_DEALER2               1024
#define IDC_LIST_REMAINING              1026
#define IDC_EDIT_WOHIT                  1027
#define IDC_EDIT_TOTAL                  1028
#define IDC_CHECK_AUTOPLAY              1029
#define IDC_EDIT_DEALERW                1030
#define IDC_EDIT_MEW                    1031
#define IDC_EDIT_PROBTOTAL              1032
#define IDC_CHECK_ALLMANUAL             1032
#define IDC_EDIT_DEALER_CARDS           1033
#define IDC_EDIT_ME_CARDS               1034
#define IDC_BUTTON_NEW_HAND             1035
#define IDC_BUTTON_RESHUFFLE            1036
#define IDC_RADIO_HIT                   1038
#define IDC_RADIO_DOUBLE                1039
#define IDC_EDIT_DDADVANTAGE            1040
#define IDC_EDIT_SPLITADVANTAGE         1041
#define IDC_EDIT_COMMAND                1042
#define IDC_EDIT_BJ_ADVANTAGE           1043
#define IDC_EDIT_HANDS_PLAYED           1044
#define IDC_RADIO_SPLIT                 1045
#define IDC_EDIT_TIME_PLAYED            1045
#define IDC_LIST_DECISION               1046
#define IDC_RADIO_ACE                   1047
#define IDC_EDIT_WON                    1048
#define IDC_EDIT_LOST                   1049
#define IDC_EDIT_WHIT                   1051
#define IDC_EDIT_WAGER                  1052
#define IDC_SPIN_WAGER                  1053
#define IDC_CHECK_HIT_SOFT17            1054
#define IDC_COMBO_DOUBLING              1056
#define IDC_COMBO_SPLITTING             1057
#define IDC_EDIT_NUM_DECKS              1058
#define IDC_CHECK_DAS_ALLOWED           1059
#define IDC_BUTTON_D1                   1060
#define IDC_BUTTON_D2                   1061
#define IDC_BUTTON_D3                   1062
#define IDC_BUTTON_D4                   1063
#define IDC_BUTTON_D5                   1064
#define IDC_BUTTON_D6                   1065
#define IDC_BUTTON_D7                   1066
#define IDC_BUTTON_D8                   1067
#define IDC_BUTTON_D9                   1068
#define IDC_BUTTON_D10                  1069
#define IDC_BUTTON_M1                   1070
#define IDC_BUTTON_M2                   1071
#define IDC_BUTTON_M3                   1072
#define IDC_BUTTON_M4                   1073
#define IDC_BUTTON_M5                   1074
#define IDC_BUTTON_M6                   1075
#define IDC_BUTTON_M7                   1076
#define IDC_BUTTON_M8                   1077
#define IDC_BUTTON_M9                   1078
#define IDC_BUTTON_M10                  1079
#define IDC_BUTTON_O1                   1080
#define IDC_BUTTON_O2                   1081
#define IDC_BUTTON_O3                   1082
#define IDC_BUTTON_O4                   1083
#define IDC_BUTTON_O5                   1084
#define IDC_BUTTON_O6                   1085
#define IDC_BUTTON_O7                   1086
#define IDC_BUTTON_O8                   1087
#define IDC_BUTTON_O9                   1088
#define IDC_BUTTON_O10                  1089
#define IDC_LIST_MISTAKES               1090
#define IDC_BUTTON_STAND                1091
#define IDC_LIST_MISTAKES_STANDARD      1091
#define IDC_BUTTON_HIT                  1092
#define IDC_BUTTON_DOUBLE               1093
#define IDC_BUTTON_SPLIT                1094
#define IDC_BUTTON_BET                  1095
#define IDC_BUTTON_CHANGE_STRATEGY      1096
#define IDC_CHECK_CAN_DOUBLE_ACES       1097
#define IDC_COMBO_STANDARD_STRATEGY     1098
#define IDC_CHECK_CAN_DOUBLE_1011       1098
#define IDC_CHECK_CAN_DOUBLE_9          1099
#define IDC_STATIC1                     1099
#define IDC_CHECK_CAN_DOUBLE_ACES4      1100
#define IDC_STATIC2                     1100
#define IDC_CHECK_CAN_SPLIT_ACES        1101
#define IDC_STATICPRO2                  1101
#define IDC_STATICPRO                   1102
#define IDC_STATICPRO3                  1103
#define ID_1                            32771
#define ID_2                            32772
#define ID_3                            32773
#define ID_4                            32774
#define ID_5                            32775
#define ID_6                            32776
#define ID_7                            32777
#define ID_8                            32778
#define ID_9                            32779
#define ID_10                           32780
#define ID_MEFOCUS                      32781
#define ID_DEALERFOCUS                  32782
#define ID_HANDOVER                     32783
#define ID_CALCULATE                    32784
#define ID_WON                          32785
#define ID_LOST                         32786
#define ID_NOBODY                       32787
#define ID_HAND_DEALER                  32788
#define ID_HAND_ME                      32789
#define ID_HAND_OTHER                   32790
#define ID_SETTINGS_CASINORULES         32791
#define ID_MENU_DECK_SETTINGS           32795
#define ID_MENU_DECK_RESHUFFLE          32796
#define ID_MENU_VIEWMISTAKES            32797
#define ID_MENUITEM_VIEW_SETTINGS       32799
#define ID_MENUITEM_VIEW_MISTAKES       32800
#define ID_MENUITEM_VIEW_PRACTICE       32801
#define ID_MENUITEM_MISTAKES_VIEW_SESSION 32802
#define ID_MENUITEM_MISTAKES_VIEW_DAY   32803
#define ID_MENUITEM_MISTAKES_VIEW_WEEK  32804
#define ID_MENUITEM_MISTAKES_VIEW_MONTH 32805
#define ID_MENU_SHOW_COUNT              32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
